### ISSUE TITLE
[DOC-FIX] `model_store` different between torchserve and mlflow-torchserve

### ISSUE THREAD

**Issue by savagej** [mlflow/mlflow-torchserve#60]
When first trying to get the BertNewsClassification example working, I started torchserve in the root directory, then tried to run mlflow deployments create in the examples directory. This resulted in the `model_store` directories being different between `torchserve` and `mlflow-torchserve` which resulted in a `Unable to register the model` error. However, the error messages that are printed out by torchserve didn’t point me towards this obvious mistake. I think one simple way that could guide new users towards realising this disconnect before doing it could be adding an example where the `EXPORT_PATH` is explicitly set.
```
mlflow deployments create -t torchserve -m <model uri> --name DEPLOYMENT_NAME -C 'MODEL_FILE=<model file path>' -C 'HANDLER=<handler file path>' -C 'EXPORT_PATH=<torchserve model_store path>'
```

We ran into this problem again though when containerising our setup, and again the unhelpful torchserve errors didn’t guide us to the problem, we only realised the issue because we had made the above mistake earlier. Would it be worth adding a warning here https://github.com/mlflow/mlflow-torchserve/blob/master/mlflow_torchserve/__init__.py#L352 to let users know that the directory is being created and might not be doing what they want.  
Would there be any other way to sanity check that the torchserve `model_store` directory lines up with the one being used by mlflow-torchserve to catch these errors before even starting? Or should it fall to torchserve to give a better warning that the `model_store` is empty?

Here is the error output from torchserve and mlflow-torchserve when this happens:
```
2021-03-02 21:50:30,422 [INFO ] epollEventLoopGroup-3-1 ACCESS_LOG - /127.0.0.1:33028 "GET /models/news_classification_test/all HTTP/1.1" 404 9
2021-03-02 21:50:30,422 [INFO ] epollEventLoopGroup-3-1 TS_METRICS - Requests4XX.Count:1|#Level:Host|#hostname:john-XPS-13-9370,timestamp:null
/home/john/Documents/mlops-engineeringlab/mlflow-torchserve/examples/BertNewsClassification/model_store/news_classification_test.mar file generated successfully
2021-03-02 21:50:51,542 [INFO ] epollEventLoopGroup-3-2 ACCESS_LOG - /127.0.0.1:33032 "POST /models?url=/home/john/Documents/mlops-engineeringlab/mlflow-torchserve/examples/BertNewsClassification/model_store/news_classification_test.mar&initial_workers=1 HTTP/1.1" 404 5
2021-03-02 21:50:51,542 [INFO ] epollEventLoopGroup-3-2 TS_METRICS - Requests4XX.Count:1|#Level:Host|#hostname:john-XPS-13-9370,timestamp:null
Traceback (most recent call last):
  File "/home/john/anaconda3/envs/torchserve/bin/mlflow", line 8, in <module>
    sys.exit(cli())
  File "/home/john/anaconda3/envs/torchserve/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/john/anaconda3/envs/torchserve/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/john/anaconda3/envs/torchserve/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/john/anaconda3/envs/torchserve/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/john/anaconda3/envs/torchserve/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/john/anaconda3/envs/torchserve/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/john/anaconda3/envs/torchserve/lib/python3.9/site-packages/mlflow/deployments/cli.py", line 132, in create_deployment
    deployment = client.create_deployment(name, model_uri, flavor, config=config_dict)
  File "/home/john/anaconda3/envs/torchserve/lib/python3.9/site-packages/mlflow_torchserve/__init__.py", line 114, in create_deployment
    self.__register_model(
  File "/home/john/anaconda3/envs/torchserve/lib/python3.9/site-packages/mlflow_torchserve/__init__.py", line 408, in __register_model
    raise Exception("Unable to register the model")
Exception: Unable to register the model
```

### Willingness to contribute
The MLflow Community encourages documentation fix contributions. Would you or another member of your organization be willing to contribute a fix for this documentation issue to the MLflow TorchServe Deployment plugin code base?

- [ ] Yes. I can contribute a documentation fix independently.
- [x] Yes. I would be willing to contribute a document fix with guidance from the MLflow community.
- [ ] No. I cannot contribute a documentation fix at this time.

### URL(s) with the issue:

https://github.com/mlflow/mlflow-torchserve#create-deployment

### Description of proposal (what needs changing):
- Add an explicit mention of `EXPORT_PATH` in documentation to highlight the fact the the torchserve `model_store` directory needs to line up with the directory mlflow-torchserve is run in.
- Potentially add a warning or info when the plugin is creating the `model_store` directory
- Are there any ways to sanity check the `model_store` for the plugin lines up with the running torchserve instance?

**Comment by lromor** [comment]
Hi!  I'm having the same issue. I think that this way of providing a file path to torch serve is quite a limiting factor. A model shouldn't necessarily reside in the filesystem (but could also be a generic url (http://etcc..). torchserve [doesn't limit you in this sense](https://pytorch.org/serve/management_api.html#register-a-model) while this plugin does.

I think a good way could be to create a deployment from an mlflow pytorch flavor which stores the model directly into `.mar`.

**Comment by shrinath-suresh** [comment]
@savagej Thanks for the input. We can update the README.md files about EXPORT_PATH parameter and also add a warning in code while creating model store.

**Comment by shrinath-suresh** [comment]
@savagej Added a note on EXPORT_PATH variable in the read me files - https://github.com/mlflow/mlflow-torchserve/pull/65 . Please check and let us know.

**Comment by shrinath-suresh** [comment]
Closing the issue. Fixed using this PR  https://github.com/mlflow/mlflow-torchserve/pull/65
